default: &default
  adapter: postgresql
  encoding: unicode
  database: desaparecidosapi
  username: postgres
  password: db
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
test:
  <<: *default
  database: desaparecidosapi_test
production:
  <<: *default
